Repository codeforamerica/il-gcc-form-flow, pull requests merged in 2024-12, with the labels that each got.

#852 [CCAP-477] Set submit screen to submit-complete-final.
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/providerresponse/submit-complete.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
Labels: Ready For Review

#846 CCAP-456 and CCAP-457
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/pdf-map.yaml
  src/main/resources/templates/fragments/gcc-icons.html
  src/main/resources/templates/providerresponse/registration-basic-info-intro.html
  src/main/resources/templates/providerresponse/registration-licensed-care-location.html
  src/main/resources/templates/providerresponse/registration-licensing-info.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseAllowProviderRegistrationFlagOnJourneyTest.java
  src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOffTest.java
  src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java
  src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
Labels: Ready For Review

#855 [CCAP-458, CCAP-459, CCAP-460, CCAP-461] Create registration applicant, unlicensed-care-location, unlicensed-relationship and basic-info-intro screens
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/submission/conditions/ProviderIsRegisteringForSelf.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/fragments/gcc-icons.html
  src/main/resources/templates/providerresponse/registration-applicant.html
  src/main/resources/templates/providerresponse/registration-basic-info-intro.html
  src/main/resources/templates/providerresponse/registration-unlicensed-care-location.html
  src/main/resources/templates/providerresponse/registration-unlicensed-relationship.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseAllowProviderRegistrationFlagOnJourneyTest.java
Labels: Ready For Review

#873 Handling null submittedAt better
  src/main/java/org/ilgcc/app/submission/actions/FormatSubmittedAtDate.java
Labels: Ready For Review

#876 [CCAP-543] Handle holidays, and holidays pushing expirations to weekends, for 3 business day logic
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/test/java/org/ilgcc/app/utils/ProviderSubmissionUtilitiesTest.java
Labels: Ready For Review

#869 [CCAP-453][CCAP-439][CCAP-537] Update content on providerresponse/provider-number screen, update provider id validation logic, remove broken link
  src/main/java/org/ilgcc/app/data/ProviderRepository.java
  src/main/java/org/ilgcc/app/data/ProviderRepositoryService.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateProviderNumber.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/fragments/inputs/screenWithOneInputAndSkip.html
  src/main/resources/templates/providerresponse/ccap-registration.html
  src/main/resources/templates/providerresponse/provider-number.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
Labels: Ready For Review

#879 [CCAP-491] - scaffold provider basic info screens
  src/main/resources/flows-config.yaml
  src/main/resources/templates/providerresponse/confirm-mailing-address.html
  src/main/resources/templates/providerresponse/mailing-address.html
  src/main/resources/templates/providerresponse/provider-info.html
  src/main/resources/templates/providerresponse/registration-home-provider-dob.html
  src/main/resources/templates/providerresponse/registration-home-provider-ssn.html
  src/main/resources/templates/providerresponse/registration-service-languages.html
  src/main/resources/templates/providerresponse/registration-tax-id-ssn.html
  src/main/resources/templates/providerresponse/registration-tax-id.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
Labels: Ready For Review

#888 [CCAP-491] - add tax ein
  src/main/resources/flows-config.yaml
  src/main/resources/templates/providerresponse/registration-tax-id-ein.html
Labels: Ready For Review

#870 Fix error messages so spacing displays correctly
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/fragments/inputError.html
Labels: Ready For Review

#874 [CCAP-346] Hide text button on desktop
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/gcc/contact-provider-message.html
Labels: Ready For Review, Merge After Acceptance

#893 [CCAP-502] Do not map no response from provider for family PDF download
  src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
  src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java
Labels: Ready For Review

#896 Updating FFL to 1.5.2
  build.gradle
  src/main/resources/templates/fragments/inputs/overrides/number.html
  src/main/resources/templates/fragments/inputs/overrides/phone.html
  src/main/resources/templates/fragments/inputs/radioFieldset.html
  src/main/resources/templates/fragments/inputs/timeRange.html
  src/main/resources/templates/fragments/inputs/zipcode.html
  src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java
Labels: Ready For Review

#894 [CCAP-545] Update fake provider importer to work in dev and test, test cases, and remove flag
  src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateProviderNumber.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
  src/test/resources/application-test.yaml
Labels: Ready For Review

#900 [CCAP-551] Fix screen reader copy link announcement on JAWS and Edge
  src/main/resources/templates/gcc/contact-provider-message.html
Labels: Ready For Review

#907 [CCAP-289] Putting version and commit sha into header
  src/main/resources/application.yaml
  src/main/resources/templates/fragments/head.html
Labels: Ready For Review

#902 [CCAP-484] Print Provider Type to PDF
  src/main/java/org/ilgcc/app/pdf/ProviderTypePreparer.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/resources/pdf-map.yaml
  src/test/java/org/ilgcc/app/pdf/ProviderTypePreparerTest.java
  src/test/resources/output/test_filled_ccap.pdf
Labels: Ready For Review

#914 [CCAP-501] Announce 'Copied to clipboard' on screen reader when button is clicked
  src/main/resources/templates/gcc/contact-provider-message.html
Labels: Ready For Review

#925 where did the disabled class go?
  src/main/resources/static/assets/css/custom.css
Labels: Ready For Review

#926 [CCAP-559] - Resolves PDF Mapping issue
  src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
  src/main/resources/flows-config.yaml
Labels: Ready For Review

#933 [CCAP-464] Consolidation of error messages
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
Labels: Do not merge

#930 [CCAP-464] - Update error messages to match new messaging
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
Labels: Ready For Review

#905 [CCAP-408] Fixing date error message formatting
  build.gradle
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/fragments/inputs/checkboxFieldset.html
  src/main/resources/templates/fragments/inputs/radioFieldset.html
Labels: Ready For Review

#931 [CCAP-482] update provider response info review
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/messages.properties
  src/main/resources/templates/providerresponse/confirm-address.html
  src/main/resources/templates/providerresponse/confirm-mailing-address.html
  src/main/resources/templates/providerresponse/info-review.html
  src/main/resources/templates/providerresponse/registration-confirm-address.html
  src/main/resources/templates/providerresponse/registration-confirm-mailing-address.html
  src/main/resources/templates/providerresponse/registration-info-review.html
  src/main/resources/templates/providerresponse/resgistration-confirm-address.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
  src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java
Labels: Ready For Review

#943 [CCAP-512][CCAP-562] Homepage and FAQ updates for SDA2 w/ flag logic
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/templates/faq.html
  src/main/resources/templates/index.html
Labels: Ready For Review

#947 [CCAP-557] - Adds provider submission id to family application when provider appli…
  src/main/java/org/ilgcc/app/ProviderResponsePdfController.java
  src/main/resources/pdfs/IL-CCAP-Form.pdf
  src/test/resources/output/test_filled_ccap.pdf
Labels: Ready For Review

#942 Set Provider Type
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/pdf/ProviderTypePreparer.java
  src/main/java/org/ilgcc/app/submission/actions/SetProviderType.java
  src/main/java/org/ilgcc/app/utils/enums/ProviderType.java
  src/main/resources/flows-config.yaml
  src/test/java/org/ilgcc/app/pdf/ProviderTypePreparerTest.java
  src/test/java/org/ilgcc/app/submission/actions/SetProviderTypeTest.java
Labels: Ready For Review

#951 [CCAP-465] - implement registration home provider ssn
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateHomeProviderSSN.java
  src/main/java/org/ilgcc/app/submission/conditions/ProviderSsnRequired.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/pdf-map.yaml
  src/main/resources/templates/fragments/gcc-icons.html
  src/main/resources/templates/providerresponse/registration-home-provider-ssn.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
Labels: Ready For Review

#957 [CCAP-465] - conditionally display provider ssn based on provider type
  src/main/java/org/ilgcc/app/submission/actions/SetProviderType.java
  src/main/java/org/ilgcc/app/submission/conditions/ProviderSsnRequired.java
  src/main/resources/flows-config.yaml
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
  src/test/java/org/ilgcc/app/submission/actions/SetProviderTypeTest.java
Labels: Ready For Review

#961 [CCAP-522] - scaffold background checks and training
  src/main/resources/flows-config.yaml
  src/main/resources/templates/providerresponse/registration-checks-trainings-intro.html
  src/main/resources/templates/providerresponse/registration-checks-trainings-notice.html
  src/main/resources/templates/providerresponse/registration-convictions-info.html
  src/main/resources/templates/providerresponse/registration-convictions.html
  src/main/resources/templates/providerresponse/registration-household-add-person-info.html
  src/main/resources/templates/providerresponse/registration-household-add-person.html
  src/main/resources/templates/providerresponse/registration-household-delete-person.html
  src/main/resources/templates/providerresponse/registration-household-members.html
Labels: Ready For Review

#963 [CCAP-515] - Create registration intro screen and tests
  src/main/resources/messages.properties
  src/main/resources/templates/providerresponse/registration-checks-trainings-intro.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
Labels: Ready For Review

#964 [CCAP-516] - registration checks trainings notice
  src/main/java/org/ilgcc/app/submission/conditions/BackgroundCheckOrTrainingRequired.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/fragments/gcc-icons.html
  src/main/resources/templates/providerresponse/registration-checks-trainings-notice.html
  src/main/resources/templates/providerresponse/registration-convictions.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
Labels: Ready For Review
