Repository codeforamerica/il-gcc-form-flow, pull requests merged in 2024-09, with the labels that each got.

#490 CCAP-49 update hourly schedule component
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/java/org/ilgcc/app/pdf/ApplicantEducationSchedulePreparer.java
  src/main/java/org/ilgcc/app/pdf/ApplicantJobSchedulePreparer.java
  src/main/java/org/ilgcc/app/pdf/ChildcareSchedulePreparer.java
  src/main/java/org/ilgcc/app/pdf/ParentPartnerJobSchedulePreparer.java
  src/main/java/org/ilgcc/app/pdf/PartnerEducationSchedulePreparer.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateActivitiesClassHourlySchedule.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateActivitiesJobSchedule.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateChildcareHourlySchedule.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateHourlySchedule.java
  src/main/java/org/ilgcc/app/submission/actions/ValidatePartnerClassHourlySchedule.java
  src/main/java/org/ilgcc/app/utils/AmPmSelectOption.java
  src/main/java/org/ilgcc/app/utils/HourSelectOption.java
  src/main/java/org/ilgcc/app/utils/SchedulePreparerUtility.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/fragments/inputs/timeRange.html
  src/main/resources/templates/fragments/inputs/timeSelect.html
  src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/HourlyScheduleJourneyTest.java
  src/test/java/org/ilgcc/app/pdf/ApplicantEducationSchedulePreparerTest.java
  src/test/java/org/ilgcc/app/pdf/ApplicantJobSchedulePreparerTest.java
  src/test/java/org/ilgcc/app/pdf/ChildcareSchedulePreparerTest.java
  src/test/java/org/ilgcc/app/pdf/ParentPartnerJobSchedulePreparerTest.java
  src/test/java/org/ilgcc/app/pdf/PartnerEducationSchedulePreparerTest.java
  src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java
  src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
  src/test/java/org/ilgcc/app/utils/TimeOption.java
  src/test/resources/output/test_filled_ccap.pdf
Labels: Ready For Review

#555 [CCAP-337] Removing warning bar for Prod
  src/main/resources/templates/fragments/toolbar.html
Labels: Do not merge

#576 [CCAP-235] handle additional children
  src/main/java/org/ilgcc/app/pdf/NeedChildcareForChildren.java
  src/main/java/org/ilgcc/app/pdf/OtherFamilyMembersPreparer.java
  src/main/java/org/ilgcc/app/submission/conditions/ReachedMaxChildrenNeedingAssistance.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/fragments/gcc-icons.html
  src/main/resources/templates/gcc/children-add.html
  src/main/resources/templates/gcc/children-ccap-max-number.html
  src/test/java/org/ilgcc/app/journeys/AddFamilyMembersJourneyTest.java
  src/test/java/org/ilgcc/app/pdf/NeedChildcareForChildrenPreparerTest.java
  src/test/java/org/ilgcc/app/pdf/OtherFamilyMembersPreparerTest.java
Labels: Ready For Review

#579 CCAP-42 Remove doc upload form submit-complete.html if no documents t…
  src/main/java/org/ilgcc/app/utils/RecommendedDocumentsUtilities.java
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/submit-complete.html
  src/test/java/org/ilgcc/app/journeys/DocumentUploadConditionalLogicJourneyTest.java
Labels: Ready For Review, Needs Translation

#587 Ccap 276 map client data to fields in application pdf appendix pages
  src/main/java/org/ilgcc/app/pdf/ApplicationPreparer.java
  src/main/resources/pdf-map.yaml
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/java/org/ilgcc/app/pdf/ApplicationPreparerTest.java
  src/test/resources/output/test_filled_ccap.pdf
Labels: Ready For Review

#592 Ccap 354 add provider response field
  src/main/resources/pdfs/IL-CCAP-Form.pdf
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/resources/output/test_filled_ccap.pdf
Labels: Ready For Review

#594 [CCAP-348] - create provider response screen
  src/main/java/org/ilgcc/app/ProviderLinkController.java
  src/main/java/org/ilgcc/app/utils/enums/ProviderSubmissionStatus.java
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/fragments/gcc-icons.html
  src/main/resources/templates/provider-responses/submit-start.html
Labels: Ready For Review

#593 Add partner full name to jobs page in appendix
  src/main/java/org/ilgcc/app/pdf/ApplicationPreparer.java
  src/main/resources/pdf-map.yaml
  src/main/resources/pdfs/IL-CCAP-Form.pdf
  src/test/resources/output/test_filled_ccap.pdf
Labels: Ready For Review

#580 🛣️ Add pdf-appendix-pages
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/java/org/ilgcc/app/pdf/ApplicationPreparer.java
  src/main/java/org/ilgcc/app/utils/ReferralServicesOption.java
  src/main/resources/flows-config.yaml
  src/main/resources/pdf-map.yaml
  src/main/resources/pdfs/IL-CCAP-Form.pdf
  src/main/resources/templates/fragments/gcc-icons.html
  src/main/resources/templates/gcc/parent-info-disability.html
  src/main/resources/templates/gcc/unearned-income-referral-services.html
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/java/org/ilgcc/app/pdf/ApplicationPreparerTest.java
  src/test/resources/output/test_filled_ccap.pdf
Labels: Do not merge

#617 [CCAP-339] - Details error messages
  src/main/java/org/ilgcc/app/submission/actions/ValidateHourlySchedule.java
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/test/java/org/ilgcc/app/journeys/HourlyScheduleJourneyTest.java
Labels: Ready For Review
