Repository codeforamerica/il-gcc-form-flow, pull requests merged in 2024-03, with the labels that each got.

#101 Add "no answer" field for race/ethnicity
  build.gradle
  src/main/resources/templates/gcc/children-ccap-info.html
  src/main/resources/templates/gcc/parent-info-basic-2.html
Labels: Needs libary update

#141 Adding "parent-add-adult-details" page
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateAdultDependentBirthdate.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/children-info-basic.html
  src/main/resources/templates/gcc/parent-add-adults-detail.html
  src/main/resources/templates/gcc/parent-partner-info-basic.html
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
Labels: Open to feedback, Work in Progress

#149 Update form with PDF mappings
  src/main/resources/pdf-map.yaml
  src/main/resources/pdfs/IL-CCAP-Form.pdf
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/resources/output/test_filled_ccap.pdf
Labels: Open to feedback
