Repository codeforamerica/il-gcc-form-flow, pull requests merged in 2025-07, with the labels that each got.

#1688 [CCAP-1069] Handle unset Datadog environment variables
  src/main/resources/templates/fragments/datadogRum.html
  src/main/resources/templates/fragments/doc-upload-head.html
  src/main/resources/templates/fragments/head.html
Labels: Ready For Review

#1686 [CCAP-975] - map multiple provider responses to pdf
  src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
  src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
  src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_MultipleProvider.java
Labels: Ready For Review

#1667 [CCAP-984] - email the family when a provider responds
  src/main/java/org/ilgcc/app/email/SendProviderAgreesToCareFamilyConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/templates/ProviderAgreesToCareFamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendProviderAgreesToCareFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendProviderDidNotRespondToFamilyEmailTest.java
Labels: Ready For Review

#1699 [CCAP-1002] - email family when provider declines care
  src/main/java/org/ilgcc/app/email/SendProviderDeclinesCareFamilyConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/templates/ProviderDeclinesCareFamilyConfirmationEmailTemplate.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendProviderDeclinesCareFamilyConfirmationEmailTest.java
Labels: Ready For Review

#1693 [CCAP-1001] Update NewProviderAgreesToCareFamilyConfirmationEmailTemplate
  src/main/java/org/ilgcc/app/email/SendNewProviderAgreesToCareFamilyConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/templates/NewProviderAgreesToCareFamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/email/templates/ProviderAgreesToCareFamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/email/templates/ProviderDidNotRespondToFamilyEmailTemplate.java
  src/main/java/org/ilgcc/app/utils/SchedulePreparerUtility.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendNewProviderAgreesToCareFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendProviderAgreesToCareFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendProviderDidNotRespondToFamilyEmailTest.java
  src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
Labels: Work in Progress, Ready For Review

#1707 [CCAP-1096] Cleaning up providerPaidCcap logic
  src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
  src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
  src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java
  src/main/java/org/ilgcc/app/submission/conditions/ProviderIsRegistering.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_MultipleProvider.java
  src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_SingleProvider.java
Labels: Ready For Review

#1715 [CCAP-1018], [CCAP-1020] - send email when applying with only providers and no provider
  src/main/java/org/ilgcc/app/email/templates/FamilyConfirmationEmailNoProviderTemplate.java
  src/main/java/org/ilgcc/app/email/templates/FamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendFamilyConfirmationNoProviderEmailTest.java
Labels: Ready For Review

#1719 [CCAP-1019] - Implements Family confirmation where some providers and…
  src/main/java/org/ilgcc/app/email/templates/FamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
Labels: Ready For Review

#1739 [CCAP-1098] Cleaning up queries
  src/main/java/org/ilgcc/app/data/TransactionRepository.java
  src/main/java/org/ilgcc/app/data/TransmissionRepository.java
  src/test/java/org/ilgcc/jobs/ProviderResponseRecurringJobTest.java
Labels: Ready For Review

#1735 [CCAP-1054] Update copy for submit-confirmation.general.call-text
  src/main/resources/messages.properties
Labels: Ready For Review

#1742 [CCAP-921]- Updated the description of W-9 form on providerresponse/r…
  src/main/resources/messages.properties
Labels: Ready to Merge

#1712 [CCAP-995][CCAP-1004] Send FamilySubmissionTransmitted Confirmation Email
  src/main/java/org/ilgcc/app/data/SubmissionSenderService.java
  src/main/java/org/ilgcc/app/email/ILGCCEmail.java
  src/main/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/templates/FamilyApplicationTransmittedConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/java/org/ilgcc/app/submission/actions/SetProviderCareStartDate.java
  src/main/java/org/ilgcc/app/utils/DateUtilities.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
Labels: Ready to Merge

#1744 [CCAP-1097] Skip multi-provider and confirm-provider screens for single provider applications
  src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
  src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
  src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
  src/main/java/org/ilgcc/app/submission/conditions/MultiProviderIsEnabledAndHasMultipleProviders.java
  src/main/java/org/ilgcc/app/submission/filters/ProvidersWithChildcareSchedules.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/java/org/ilgcc/app/utils/SchedulePreparerUtility.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/flows-config.yaml
  src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
  src/test/java/org/ilgcc/app/utils/SubmissionUtilitiesTest.java
Labels: Ready For Review

#1772 [CCAP-1004] Family submission successfully transmitted to CCMS email should go for all submissions
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
Labels: Ready For Review

#1750 [CCAP-1149] When no providers have a schedule attached treat as a no provider application
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
Labels: Ready to Merge

#1747 [CCAP-1148] Handle PDF preparation and CCMS send for pre-multi-provider applications
  src/main/java/org/ilgcc/app/data/SubmissionSenderService.java
  src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
  src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_NoProvider.java
Labels: Ready to Merge

#1764 Reapply CCAP-1097 with fix for failing tests
  src/main/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmail.java
  src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
  src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
  src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
  src/main/java/org/ilgcc/app/submission/conditions/MultiProviderIsEnabledAndHasMultipleProviders.java
  src/main/java/org/ilgcc/app/submission/filters/ProvidersWithChildcareSchedules.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/java/org/ilgcc/app/utils/SchedulePreparerUtility.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/flows-config.yaml
  src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
  src/test/java/org/ilgcc/app/utils/SubmissionUtilitiesTest.java
Labels: Ready to Merge

#1776 [CCAP-1168]- Changed button copy on providerresponse/provider-id-fein , changed it from 'submit' to 'continue'.
  src/main/resources/templates/providerresponse/provider-id-fein.html
Labels: Ready to Merge

#1777 [CCAP-1057] : Update copy on the providerresponse/submit-start screen
  src/main/resources/messages.properties
Labels: Ready to Merge

#1778 [CCAP-1004] - sets provider initials in SendFamilyApplicationTransmit…
  src/main/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmail.java
  src/test/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmailTest.java
Labels: Ready to Merge

#1784 [CCAP-1148] Fix child care schedule PDF mappings
  src/main/java/org/ilgcc/app/pdf/NeedChildcareChildrenPreparer.java
Labels: Ready For Review

#1785 [CCAP-1148] Fix issues with single provider family submission and multi-provider provider response
  src/main/java/org/ilgcc/app/data/SubmissionSenderService.java
  src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
  src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
  src/main/java/org/ilgcc/app/submission/actions/GenerateDummyFamilySubmissionForDev.java
  src/main/java/org/ilgcc/app/submission/actions/SendProviderRegistrationAndFamilyPayloadToCCMS.java
  src/main/java/org/ilgcc/app/submission/actions/SetProviderSubmissionStatusAndConnectApplications.java
  src/test/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMSTest.java
Labels: Ready For Review

#1753 [CCAP-1090], [CCAP-1153] - Make sure no provider and no provider response is working
  src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
  src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
  src/main/java/org/ilgcc/app/pdf/helpers/FamilyIntendedProviderPreparerHelper.java
  src/main/java/org/ilgcc/app/submission/actions/GenerateShortLinkAndStoreProviderApplicationStatus.java
  src/main/java/org/ilgcc/app/submission/conditions/CurrentProviderHasResponded.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/java/org/ilgcc/jobs/ProviderResponseRecurringJob.java
  src/test/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_MultipleProvider.java
Labels: Ready to Merge

#1741 [CCAP-1052] - Update all "delete" link copy on builder pages to "remove"
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/activities-add-jobs.html
  src/main/resources/templates/gcc/activities-partner-add-job.html
  src/main/resources/templates/gcc/parent-add-adults.html
  src/main/resources/templates/providerresponse/registration-household-add-person.html
  src/test/java/org/ilgcc/app/journeys/GccSingleProviderJourneyTest.java
Labels: Ready to Merge

#1775 [CCAP-366] map total family size into pdf
  src/main/java/org/ilgcc/app/pdf/ApplicationPreparer.java
  src/main/java/org/ilgcc/app/utils/PreparerUtilities.java
  src/main/resources/pdf-map.yaml
  src/test/java/org/ilgcc/app/pdf/ApplicationPreparerTest.java
  src/test/resources/output/test_filled_ccap.pdf
  src/test/resources/output/test_filled_ccap_EXISTING_PROVIDER_RESPONSE.pdf
  src/test/resources/output/test_filled_ccap_NO_PROVIDER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_DAY_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_GROUP_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_CHILD_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_HOME.pdf
Labels: Ready to Merge

#1808 [CCAP-1215] Provider docs need to filter out original files if PDF modification is enabled
  src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
Labels: Ready to Merge

#1805 [CCAP-1213] - makes sure all signatures are in Central time
  src/main/java/org/ilgcc/app/pdf/ApplicationPreparer.java
  src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
  src/main/resources/pdf-map.yaml
  src/test/java/org/ilgcc/app/pdf/ApplicationPreparerTest.java
Labels: Ready to Merge

#1771 [CCAP-1050] Add sitemap with mappings for landing, faq and privacy-policy
  src/main/java/org/ilgcc/app/RobotsController.java
  src/main/java/org/ilgcc/app/SitemapController.java
  src/main/java/org/ilgcc/app/StaticPageController.java
Labels: Ready to Merge

#1810 [CCAP-986] Removing duplicate call
  src/main/java/org/ilgcc/jobs/ProviderResponseRecurringJob.java
Labels: Ready to Merge
