Repository codeforamerica/il-gcc-form-flow, pull requests merged in 2025-08, with the labels that each got.

#1822 [CCAP-1238] Updating CCMS retries from 3 to 5
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
Labels: Ready For Review

#1823 CCAP 1185 - If partner is working or in school, indicate it on PDF yes/no questions on page 5
  src/main/java/org/ilgcc/app/pdf/ParentPartnerPreparer.java
  src/main/resources/pdf-map.yaml
  src/test/resources/output/test_filled_ccap.pdf
  src/test/resources/output/test_filled_ccap_EXISTING_PROVIDER_RESPONSE.pdf
  src/test/resources/output/test_filled_ccap_NO_PROVIDER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_DAY_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_GROUP_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_CHILD_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_HOME.pdf
Labels: Ready to Merge

#1803 [CCAP-1152] - Change SDA phone number in FAQ.
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
Labels: Ready to Merge

#1804 [CCAP-1166] : Update icon and help text formatting on providerresponse/multiple-providers screen
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/templates/providerresponse/multiple-providers.html
Labels: Ready to Merge

#1819 [CCAP-1231] Hiding checkbox when there's only 1 day selected for jobs and class schedules
  src/main/resources/templates/fragments/screens/activities-class-hourly-schedule.html
  src/main/resources/templates/gcc/activities-class-hourly-schedule.html
  src/main/resources/templates/gcc/activities-job-hourly-schedule.html
  src/main/resources/templates/gcc/activities-partner-class-hourly-schedule.html
  src/main/resources/templates/gcc/activities-partner-job-hourly-schedule.html
  src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccNoProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccSingleProviderJourneyTest.java
Labels: Ready to Merge

#1830 [CCAP-1183] If family is applying with multiple providers, indicate on page 2 of application PDF
  src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
  src/main/resources/pdf-map.yaml
  src/test/resources/output/test_filled_ccap.pdf
  src/test/resources/output/test_filled_ccap_EXISTING_PROVIDER_RESPONSE.pdf
  src/test/resources/output/test_filled_ccap_NO_PROVIDER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_DAY_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_GROUP_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_CHILD_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_HOME.pdf
Labels: Ready to Merge

#1844 [CCAP-1209] Make sitemap discoverable with full URL in prod
  src/main/java/org/ilgcc/app/RobotsController.java
  src/test/java/org/ilgcc/app/RobotsControllerTest.java
Labels: Ready For Review

#1842 [CCAP-1184] Map provider county - with working tests
  src/main/java/org/ilgcc/app/pdf/helpers/ProviderApplicationPreparerHelper.java
  src/main/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRName.java
  src/main/java/org/ilgcc/app/submission/actions/SetProviderCounty.java
  src/main/resources/flows-config.yaml
  src/main/resources/pdf-map.yaml
  src/test/java/org/ilgcc/app/journeys/ProviderresponseExistingProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegisteringLicenseChildCareCenterJourneyTest.java
  src/test/resources/output/test_filled_ccap.pdf
  src/test/resources/output/test_filled_ccap_EXISTING_PROVIDER_RESPONSE.pdf
  src/test/resources/output/test_filled_ccap_NO_PROVIDER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_DAY_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_GROUP_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_CHILD_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSE_EXEMPT_HOME.pdf
Labels: Ready to Merge

#1815 [CCAP-996] send an email to a provider when they respond to a family application
  src/main/java/org/ilgcc/app/email/ILGCCEmail.java
  src/main/java/org/ilgcc/app/email/SendEmail.java
  src/main/java/org/ilgcc/app/email/SendProviderConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/SendProviderRespondedConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/templates/FamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/email/templates/NewProviderConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/email/templates/ProviderConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/email/templates/ProviderRespondedConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/submission/actions/SendNewProviderAndFamilyConfirmationEmails.java
  src/main/java/org/ilgcc/app/submission/actions/SendProviderAndFamilyEmails.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendNewProviderAgreesToCareFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendNewProviderConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendProviderConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendProviderRespondedConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
Labels: Ready to Merge

#1838 [CCAP-997] - send email to provider when application is transmitted
  src/main/java/org/ilgcc/app/email/ILGCCEmail.java
  src/main/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedProviderConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/templates/FamilyApplicationTransmittedProviderConfirmationTemplate.java
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedProviderConfirmationTest.java
Labels: Ready to Merge

#1824 [CCAP-1241] - only maps parent partner data if qualifying partner
  src/main/java/org/ilgcc/app/pdf/ParentPartnerPreparer.java
  src/test/java/org/ilgcc/app/pdf/ParentPartnerPreparerTest.java
  src/test/resources/output/test_filled_ccap_NO_PROVIDER.pdf
Labels: Ready to Merge

#1860 [CCAP-1276] Remove unused workitem lookup job code
  src/main/java/org/ilgcc/jobs/EnqueueTransactionWorkItemLookupJob.java
  src/main/java/org/ilgcc/jobs/TransactionWorkItemRecurringJob.java
Labels: Ready to Merge

#1865 [CCAP-1249] Provider with no schedule not treated properly in response flow
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
Labels: Ready For Review, Ready to Merge

#1847 [CCAP-963]- Licensed providers should not see providerresponse/regisration-convictions screen
  src/main/java/org/ilgcc/app/submission/conditions/ProviderShouldNotSeeConvictionsScreen.java
  src/main/resources/flows-config.yaml
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegisteringLicensedChildCareCenterTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegisteringLicensedDayCareHomeTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegisteringLicensedGroupCareHomeJourneyTest.java
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_CHILD_CARE_CENTER.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_DAY_CARE_HOME.pdf
  src/test/resources/output/test_filled_ccap_REGISTERING_LICENSED_GROUP_CARE_HOME.pdf
Labels: Ready to Merge

#1869 [CCAP-1242] - enable cohort 2
  sample.env
  src/main/java/org/ilgcc/app/data/importer/FakeResourceOrganizationAndCountyData.java
  src/test/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRNameTest.java
Labels: Ready to Merge

#1875 [CCAP-1243] - Keep counties language when enable new sda flag is off
  src/main/resources/messages.properties
  src/main/resources/templates/faq.html
  src/main/resources/templates/index.html
Labels: Ready to Merge

#1861 [CCAP-1196]- The “remove” links on the gcc/parent-add-adults screen announce the list item that the links refers to
  src/main/resources/templates/gcc/parent-add-adults.html
  src/main/resources/templates/gcc/providers-add.html
  src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccSingleProviderJourneyTest.java
Labels: Ready to Merge

#1862 [CCAP-1197] Make remove links unambiguous for screen reader users on activities "add-jobs" screens
  src/main/resources/templates/gcc/activities-add-jobs.html
  src/main/resources/templates/gcc/activities-partner-add-job.html
  src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccSingleProviderJourneyTest.java
Labels: Ready to Merge

#1885 [CCAP-1304] Handle selenium putting a null into the json
  src/main/java/org/ilgcc/app/email/templates/FamilyApplicationTransmittedConfirmationEmailTemplate.java
Labels: Ready For Review

#1884 [CCAP-1303] Only send provider CCMS email if a provider has actually responded
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
Labels: Ready For Review

#1870 [CCAP-1202]: Make remove and delete file links announce file name for…
  src/main/resources/templates/fragments/inputs/overrides/fileUploader.html
Labels: Ready to Merge

#1874 [CCAP-1201]- The “remove” links on the providerresponse/registration-household-add-person screen now announces the first and last name of the person.
  src/main/resources/templates/providerresponse/registration-household-add-person.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
Labels: Ready to Merge

#1876 [CCAP-1199] : Make remove and edit links unambiguous for screen reader users on gcc/providers-add screen
  src/main/resources/templates/gcc/providers-add.html
  src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java
Labels: Ready to Merge

#1880 [CCAP-1198]- The “remove” links on the gcc/children-add screen annou…
  src/main/resources/templates/gcc/children-add.html
  src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccSingleProviderJourneyTest.java
Labels: Ready to Merge

#1878 [CCAP-1169] Wrong version of the provider submit confirmation page is…
  src/main/resources/templates/providerresponse/submit-confirmation.html
Labels: Ready to Merge

#1909 [CCAP-1245] - removes default html 5 behavior of inc or dec numbers
  src/main/resources/static/assets/css/custom.css
Labels: Ready For Review

#1908 [CCAP-1261] Add icon to children-ccap-child-other-ed page
  src/main/resources/templates/gcc/children-ccap-child-other-ed.html
Labels: Ready to Merge

#1897 [CCAP-1263] Update ValidateBirthdate to throw null value errors
  src/main/java/org/ilgcc/app/submission/actions/ValidateBirthdate.java
  src/test/java/org/ilgcc/app/submission/actions/ValidateBirthdateTest.java
Labels: Ready to Merge

#1919 [CCAP-1336] Adding some logging to CCMSSubmissionPayloadTransactionJob
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
Labels: Ready For Review

#1917 [CCAP-1259] Update FFL version to fix PDF stamper issue
  build.gradle
  src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java
Labels: Ready to Merge

#1902 [CCAP-1260] - update transmission confirmation email to have differen…
  src/main/java/org/ilgcc/app/email/templates/FamilyApplicationTransmittedConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/test/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmailTest.java
Labels: Ready to Merge

#1925 [CCAP-768] Update the descriptions for document types on upload-recommended-docs page
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/doc-upload-recommended-docs.html
  src/test/java/org/ilgcc/app/journeys/DocumentUploadConditionalLogicJourneyTest.java
Labels: Ready to Merge
