Repository codeforamerica/il-gcc-form-flow, pull requests merged in 2025-03, with the labels that each got.

#1238 [CCAP-674] Show providerresponse/registration-submit-confirmation as final screen when an existing provider responds
  src/main/resources/application.yaml
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/fragments/gcc-icons.html
  src/main/resources/templates/fragments/screens/registration-submit-confirmation.html
  src/main/resources/templates/fragments/screens/submit-complete-final-fragment.html
  src/main/resources/templates/providerresponse/registration-submit-confirmation.html
  src/main/resources/templates/providerresponse/submit-complete-final.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
Labels: Ready For Review

#1244 [CCAP-695] Update onboarding-provider-info-confirm.html screen
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/onboarding-provider-info-confirm.html
Labels: Ready For Review

#1245 [CCAP-598] Require SSN to be actually valid
  build.gradle
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-staging.yaml
Labels: Ready For Review

#1242 [CCAP-657] Send Application Submission payload to CCMS API endpoint
  src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java
  src/main/java/org/ilgcc/app/data/ccms/CCMSTransaction.java
  src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
  src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java
  src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3.java
  src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayload.java
  src/main/java/org/ilgcc/app/utils/DateUtilities.java
  src/main/java/org/ilgcc/app/utils/enums/CCMSEndpoints.java
  src/main/java/org/ilgcc/app/utils/enums/CCMSRequestHeaders.java
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
  src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
  src/main/resources/application.yaml
  src/main/resources/flows-config.yaml
  src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java
  src/test/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMSTest.java
  src/test/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3Test.java
  src/test/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayloadTest.java
  src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobTest.java
  src/test/resources/application-test.yaml
Labels: Ready For Review

#1264 [CCAP-695] Fixing spacing
  src/main/resources/templates/gcc/onboarding-provider-info-confirm.html
Labels: Ready For Review

#1261 [CCAP-704] Update provider table and provider importer to support site-administered provider orgs
  .gitignore
  src/main/java/org/ilgcc/app/data/CCMSDataService.java
  src/main/java/org/ilgcc/app/data/CCMSDataServiceImpl.java
  src/main/java/org/ilgcc/app/data/Provider.java
  src/main/java/org/ilgcc/app/data/importer/CountyAndZipCodeImporter.java
  src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java
  src/main/java/org/ilgcc/app/data/importer/ImporterUtils.java
  src/main/java/org/ilgcc/app/data/importer/ProviderImporter.java
  src/main/java/org/ilgcc/app/data/importer/ResourceOrganizationImporter.java
  src/main/java/org/ilgcc/app/submission/router/ApplicationRouterService.java
  src/main/java/org/ilgcc/app/submission/router/ApplicationRoutingServiceImpl.java
  src/main/resources/db/migration/V2025.03.06.13.54__Update_providers_add_site_provider_org_id.sql
  src/test/java/org/ilgcc/app/data/ProviderAndResourceOrganizationIntegrationTest.java
  src/test/java/org/ilgcc/app/data/ProviderAndSiteAdministeredResourceOrganizationTest.java
  src/test/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRNameTest.java
Labels: Ready For Review

#1265 [CCAP-591] Implement TransactionWorkItemRecurringJob and a JobFilter for failure notifications
  src/main/java/org/ilgcc/app/config/JobrunrConfig.java
  src/main/java/org/ilgcc/app/data/Transaction.java
  src/main/java/org/ilgcc/app/data/TransactionRepository.java
  src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
  src/main/java/org/ilgcc/jobs/EnqueueTransactionWorkItemLookupJob.java
  src/main/java/org/ilgcc/jobs/JobRetriesFailedFilter.java
  src/main/java/org/ilgcc/jobs/TransactionWorkItemRecurringJob.java
  src/main/resources/db/migration/V2025.03.06.16.17.17__Change_WorkItemID_Column_to_VARCHAR_from_UUID_in_Transaction_Table.sql
Labels: Ready For Review

#1279 [CCAP-697] Create new children-info-assistance screen
  src/main/java/org/ilgcc/app/pdf/OtherFamilyMembersPreparer.java
  src/main/java/org/ilgcc/app/submission/actions/GenerateDummyFamilySubmissionForDev.java
  src/main/java/org/ilgcc/app/submission/conditions/NeedsFinancialAssistanceForChild.java
  src/main/java/org/ilgcc/app/submission/conditions/ReachedMaxChildrenNeedingAssistance.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/templates/gcc/children-info-assistance.html
  src/main/resources/templates/gcc/children-info-basic.html
  src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/AddFamilyMembersJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/DocumentUploadConditionalLogicJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccNoProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/HourlyScheduleJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderResponseShortLinkJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/SignatureJourneyTest.java
  src/test/java/org/ilgcc/app/pdf/ChildcareSchedulePreparerTest.java
  src/test/java/org/ilgcc/app/pdf/NeedChildcareForChildrenPreparerTest.java
  src/test/java/org/ilgcc/app/pdf/OtherFamilyMembersPreparerTest.java
  src/test/java/org/ilgcc/app/submission/actions/RemoveIncompleteChildIterationsTest.java
  src/test/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/submission/actions/SendProviderAgreesToCareFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/submission/actions/SendProviderConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/utils/ProviderSubmissionUtilitiesTest.java
Labels: Ready For Review

#1281 Generate fake county/zipcode data in heroku environment
  src/main/java/org/ilgcc/app/data/importer/FakeResourceOrganizationAndCountyData.java
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccNoProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRNameTest.java
  src/test/java/org/ilgcc/app/submission/actions/ValidateZipCodeTest.java
  src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java
Labels: Ready For Review

#1289 Don't log full request body in CCMS sendRequest error
  src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java
Labels: Ready For Review

#1290 Set the timing for the delayed CCMS payload job with environment variable
  src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java
  src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayload.java
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
  src/main/resources/application.yaml
Labels: Ready For Review

#1284 [CCAP-675] Send provider registration supporting documents with family submission to CCMS
  src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
  src/main/java/org/ilgcc/app/submission/actions/GenerateDummyFamilySubmissionForDev.java
  src/main/java/org/ilgcc/app/submission/actions/SendProviderRegistrationAndFamilyPayloadToCCMS.java
  src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java
  src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayload.java
  src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
  src/main/resources/flows-config.yaml
  src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java
Labels: Ready For Review

#1286 [CCAP-368] Added Relationship in other info to Family Dependent
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/java/org/ilgcc/app/pdf/OtherFamilyMembersPreparer.java
  src/main/java/org/ilgcc/app/utils/AdultDependentRelationshipOption.java
  src/main/java/org/ilgcc/app/utils/ChildRelationshipOption.java
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/pdf-map.yaml
  src/main/resources/templates/gcc/children-info-basic.html
  src/main/resources/templates/gcc/parent-add-adults-detail.html
  src/test/java/org/ilgcc/app/journeys/AddFamilyMembersJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccNoProviderFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/HourlyScheduleJourneyTest.java
  src/test/resources/output/test_filled_ccap.pdf
Labels: Ready For Review

#1293 [CCAP-615] Skip ccap start date screens if no provider is true
  src/main/java/org/ilgcc/app/submission/conditions/NoProviderChosen.java
  src/main/resources/flows-config.yaml
  src/main/resources/templates/gcc/children-childcare-hourly-schedule.html
  src/main/resources/templates/gcc/children-childcare-weekly-schedule.html
  src/test/java/org/ilgcc/app/journeys/GccNoProviderFlowJourneyTest.java
Labels: Ready For Review

#1295 [CCAP-647] Update provider response section
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/index.html
Labels: Open to feedback, Ready For Review

#1297 [CCAP-647] changed spacing to 25 between label and textbox
  src/main/resources/templates/index.html
Labels: Ready For Review

#1302 [CCAP-476] - update design response screen
  build.gradle
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/gcc/doc-upload-add-files.html
  src/main/resources/templates/providerresponse/mailing-address.html
  src/main/resources/templates/providerresponse/provider-number.html
  src/main/resources/templates/providerresponse/registration-checks-trainings-notice.html
  src/main/resources/templates/providerresponse/registration-doc-upload-add-files.html
  src/main/resources/templates/providerresponse/registration-tax-id.html
  src/main/resources/templates/providerresponse/response.html
  src/main/resources/templates/providerresponse/submit-start.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
Labels: Ready For Review

#1305 [CCAP-709] Truncate First Name and Last Name in CCMS API Submission Request
  src/main/java/org/ilgcc/app/data/ccms/CCMSTransaction.java
  src/main/java/org/ilgcc/app/utils/FileNameUtility.java
Labels: Ready For Review

#1307 [CCAP-718] Include client confirmation code as part of folder name in sharepoint
  src/main/java/org/ilgcc/app/utils/FileNameUtility.java
  src/test/java/org/ilgcc/app/utils/FileNameUtilityTest.java
Labels: Ready For Review

#1312 [CCAP-495] Send confirmation email to family with no provider
  src/main/java/org/ilgcc/app/email/ILGCCEmail.java
  src/main/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmail.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/test/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmailTest.java
Labels: Ready For Review

#1319 [CCAP-708] - send family an email when provider declines care
  src/main/java/org/ilgcc/app/email/ILGCCEmail.java
  src/main/java/org/ilgcc/app/email/ILGCCEmailTemplate.java
  src/main/java/org/ilgcc/app/email/SendEmail.java
  src/main/java/org/ilgcc/app/email/SendFamilyConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/SendFamilyConfirmationNoProviderEmail.java
  src/main/java/org/ilgcc/app/email/SendProviderAgreesToCareFamilyConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/SendProviderConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/SendProviderDeclinesCareFamilyConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/templates/FamilyConfirmationEmailNoProviderTemplate.java
  src/main/java/org/ilgcc/app/email/templates/FamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/email/templates/ProviderAgreesToCareFamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/email/templates/ProviderConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/email/templates/ProviderDeclinesCareFamilyConfirmationEmailTemplate.java
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmail.java
  src/main/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmails.java
  src/main/java/org/ilgcc/app/submission/actions/SendProviderAgreesToCareFamilyConfirmationEmail.java
  src/main/java/org/ilgcc/app/submission/actions/SendProviderAndFamilyEmails.java
  src/main/java/org/ilgcc/app/submission/actions/SendProviderConfirmationEmail.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendFamilyConfirmationNoProviderEmailTest.java
  src/test/java/org/ilgcc/app/email/SendProviderAgreesToCareFamilyConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendProviderConfirmationEmailTest.java
  src/test/java/org/ilgcc/app/email/SendProviderDeclinesCareFamilyConfirmationEmailTest.java
Labels: Ready For Review

#1330 [CCAP-722] - add new provider messaging flag and scaffold screens
  src/main/java/org/ilgcc/app/submission/conditions/EnableProviderMessagingFlagOn.java
  src/main/resources/application.yaml
  src/main/resources/flows-config.yaml
  src/main/resources/templates/gcc/parent-confirm-provider-number.html
  src/main/resources/templates/gcc/submit-confirm-provider-email.html
  src/main/resources/templates/gcc/submit-confirmation.html
  src/main/resources/templates/gcc/submit-contact-method.html
  src/main/resources/templates/gcc/submit-contact-provider-email-confirmation.html
  src/main/resources/templates/gcc/submit-contact-provider-email.html
  src/main/resources/templates/gcc/submit-contact-provider-text-confirmation.html
  src/main/resources/templates/gcc/submit-contact-provider-text.html
  src/main/resources/templates/gcc/submit-provider-info-edit.html
Labels: Ready For Review

#1332 [CCAP-732] - update submit intro screen to include contactProvider co…
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/submit-intro.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Ready For Review

#1334 [CCAP-721] Add onboarding-2-part.html screen and update tests
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/gcc/onboarding-2-part.html
  src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/GccNoProviderFlowJourneyTest.java
Labels: Ready For Review

#1335 [CCAP-723] - create submit-contact-method screen and corresponding tests
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/submit-contact-method.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Ready For Review

#1336 [CCAP-739] - submit-edit-provider-email screen
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/fragments/screens/child-care-provider-info.html
  src/main/resources/templates/gcc/onboarding-provider-info.html
  src/main/resources/templates/gcc/submit-edit-provider-email.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Ready For Review

#1338 [CCAP-733] - submit contact provider email
  src/main/java/org/ilgcc/app/submission/conditions/DisplaySubmitContactProviderEmailScreen.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/submit-contact-provider-email.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
  src/test/java/org/ilgcc/app/submission/actions/DisplaySubmitContactProviderEmailScreenTest.java
Labels: Ready For Review

#1340 updates logs after recent alerts
  src/main/java/org/ilgcc/app/email/SendEmail.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
Labels: Ready For Review

#1347 [CCAP-736] - implements submit-share-confirmation-code screen
  src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaOther.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/submit-confirmation.html
  src/main/resources/templates/gcc/submit-share-confirmation-code.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Merge After Acceptance

#1341 [CCAP-724] - submit confirm provider email
  src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaEmail.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/submit-confirm-provider-email.html
  src/main/resources/templates/gcc/submit-provider-info-edit.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Merge After Acceptance
