Repository codeforamerica/il-gcc-form-flow, pull requests merged in 2025-04, with the labels that each got.

#1343 [CCAP-734] Create New submit-contact-provider-email-confirmation screen
  src/main/resources/application-dev.yaml
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/gcc/submit-contact-provider-email-confirmation.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Ready For Review, Merge After Acceptance

#1355 [CCAP-741] Add parent-confirm-provider-number-screen
  src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaText.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/gcc/parent-confirm-provider-number.html
  src/main/resources/templates/gcc/submit-confirm-provider-email.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
  src/test/java/org/ilgcc/app/submission/conditions/ContactProviderViaTextTest.java
Labels: Ready For Review

#1359 [CCAP-740] create new submit-contact-provider-text-confirmation screen
  src/main/resources/messages.properties
  src/main/resources/static/assets/css/custom.css
  src/main/resources/templates/gcc/submit-contact-provider-text-confirmation.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Ready For Review

#1360 [CCAP-727] - Send automatic email notification to provider
  src/main/java/org/ilgcc/app/email/ILGCCEmail.java
  src/main/java/org/ilgcc/app/email/SendAutomatedProviderOutreachEmail.java
  src/main/java/org/ilgcc/app/email/SendProviderConfirmationEmail.java
  src/main/java/org/ilgcc/app/email/templates/AutomatedProviderOutreachEmailTemplate.java
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/java/org/ilgcc/app/submission/actions/SendAutomatedProviderEmail.java
  src/main/java/org/ilgcc/app/submission/conditions/hasConfirmedProviderEmail.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/submit-confirm-provider-email.html
  src/main/resources/templates/gcc/submit-contact-provider-email-confirmation.html
  src/test/java/org/ilgcc/app/email/SendAutomatedProviderOutreachEmailTest.java
Labels: Ready For Review

#1348 [CCAP-735] create new submit-contact-provider-text screen
  src/main/java/org/ilgcc/app/submission/actions/ValidatePhoneNumberNotBlank.java
  src/main/java/org/ilgcc/app/submission/conditions/DisplaySubmitContactProviderTextScreen.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/submit-contact-provider-text.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
  src/test/java/org/ilgcc/app/submission/actions/ValidatePhoneNumberNotBlankTest.java
  src/test/java/org/ilgcc/app/submission/conditions/DisplaySubmitContactProviderTextScreenTest.java
Labels: Ready For Review

#1374 [CCAP-776] adding some logging for CCMS
  src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java
Labels: Ready For Review

#1369 [CCAP-774] Handle submissions without transmissions because CCMS was the only thing turned on
  src/main/java/org/ilgcc/app/data/TransactionRepository.java
  src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
  src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
  src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobTest.java
Labels: Ready For Review

#1353 [CCAP-744] - change step count
  src/main/resources/application.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/gcc/activities-parent-intro.html
  src/main/resources/templates/gcc/children-info-intro.html
  src/main/resources/templates/gcc/contact-provider-intro.html
  src/main/resources/templates/gcc/no-provider-intro.html
  src/main/resources/templates/gcc/parent-info-intro.html
  src/main/resources/templates/gcc/submit-intro.html
  src/main/resources/templates/gcc/unearned-income-intro.html
Labels: Ready For Review

#1390 [CCAP-774] Making the No Provider Response Job handle CCMS integration better
  src/main/java/org/ilgcc/app/data/JobrunrJobRepository.java
  src/main/java/org/ilgcc/app/data/TransactionRepository.java
  src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
  src/main/java/org/ilgcc/app/data/TransmissionRepository.java
  src/main/java/org/ilgcc/app/data/TransmissionRepositoryService.java
  src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
  src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
  src/test/java/org/ilgcc/app/utils/ProviderSubmissionUtilitiesTest.java
  src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobTest.java
Labels: Ready For Review

#1404 [CCAP-701] Clean up code for handling links to the provider response
  src/main/java/org/ilgcc/app/ProviderLinkController.java
Labels: Ready For Review

#1409 [CCAP-802] DTS job regenerates presignedUrl each time the job runs
  src/main/java/org/ilgcc/jobs/PdfTransmissionJob.java
  src/test/java/org/ilgcc/jobs/PdfTransmissionJobTest.java
Labels: Ready For Review

#1419 [CCAP-805] Able to submit multiple provider responses with same short code
  src/main/java/org/ilgcc/app/submission/actions/SendProviderRegistrationAndFamilyPayloadToCCMS.java
Labels: Ready For Review

#1422 [CCAP-737] Adjust the CTA on the final provider messaging step
  src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaEmail.java
  src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaOther.java
  src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaText.java
  src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/templates/gcc/submit-contact-provider-email-confirmation.html
  src/main/resources/templates/gcc/submit-contact-provider-text-confirmation.html
  src/main/resources/templates/gcc/submit-share-confirmation-code.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Ready For Review

#1415 [CCAP-731] Handle doc upload errors when a users' session is expired
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/templates/fragments/inputs/overrides/fileUploader.html
Labels: Ready For Review

#1420 [CCAP-743] Update the content on the doc-upload-recommended-docs screen
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/templates/providerresponse/registration-doc-upload-recommended-docs.html
Labels: Ready For Review

#1428 [CCAP-822] Save the confirmation code when skipping the confirmation code screen
  src/main/java/org/ilgcc/app/submission/conditions/ShouldSkipConfirmationCode.java
Labels: Ready For Review

#1412 [CCAP-315][CCAP-198] Fixing hero images on the homepage
  src/main/resources/static/assets/css/custom.css
  src/main/resources/static/assets/images/mother-baby-smiling.svg
  src/main/resources/templates/index.html
Labels: Merge After Acceptance

#1410 [CCAP-760] - when fam chooses no provider, after submit contact provi…
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/fragments/screens/choose-messaging-method.html
  src/main/resources/templates/fragments/screens/find-provider.html
  src/main/resources/templates/gcc/after-submit-contact-provider.html
  src/main/resources/templates/gcc/submit-contact-method.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Ready For Review

#1431 [CCAP-759] Move email trigger for family confirmation emails
  src/main/resources/flows-config.yaml
Labels: Ready For Review

#1432 [CCAP-823] - direct families to next steps when enable provider flag …
  src/main/resources/flows-config.yaml
  src/main/resources/templates/gcc/doc-upload-recommended-docs.html
  src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
Labels: Merge After Acceptance

#1437 [CCAP-716] - email notifications for new processing orgs
  sample.env
  src/main/java/org/ilgcc/app/data/CCMSDataService.java
  src/main/java/org/ilgcc/app/data/CCMSDataServiceImpl.java
  src/main/java/org/ilgcc/app/data/ResourceOrganizationTransaction.java
  src/main/java/org/ilgcc/app/data/TransactionRepository.java
  src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
  src/main/java/org/ilgcc/app/email/ILGCCEmail.java
  src/main/java/org/ilgcc/app/email/templates/DailyNewApplicationsProviderEmailTemplate.java
  src/main/java/org/ilgcc/app/submission/router/ApplicationRoutingServiceImpl.java
  src/main/java/org/ilgcc/app/utils/DateUtilities.java
  src/main/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJob.java
  src/main/java/org/ilgcc/jobs/SendRecurringEmailJob.java
  src/main/resources/application.yaml
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/data/ApplicationRoutingServiceImplTest.java
  src/test/java/org/ilgcc/app/email/DailyNewApplicationsProviderEmailTemplateTest.java
  src/test/java/org/ilgcc/app/email/SendAutomatedProviderOutreachEmailTest.java
  src/test/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRNameTest.java
  src/test/java/org/ilgcc/app/submission/actions/ValidateZipCodeTest.java
  src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java
  src/test/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJobTest.java
Labels: Ready to Merge

#1441 [CCAP-778] Add registration-home-provider-tax-id.html
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/submission/conditions/IsLicensedOrLicenseExemptHomeCareProvider.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/providerresponse/registration-home-provider-tax-id.html
Labels: Ready For Review

#1447 [CCAP-781] Update providerresponse/registration-home-provider-ssn screen
  src/main/resources/templates/providerresponse/registration-home-provider-ssn.html
Labels: Ready For Review

#1444 [CCAP-767][CCAP-828][CCAP-829] FFL upgrade to move to Amazon sdk v2, clean up minor other bugs
  build.gradle
Labels: Ready For Review

#1435 [CCAP-711] validate provider email address
  sample.env
  src/main/java/org/ilgcc/app/email/SendGridEmailValidationService.java
  src/main/java/org/ilgcc/app/email/SendGridValidationResponseBody.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateProviderEmail.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateProviderEmailWhenInputIsPresent.java
  src/main/java/org/ilgcc/app/utils/constants/SessionKeys.java
  src/main/resources/application.yaml
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/email/SendGridEmailValidationServiceTest.java
  src/test/java/org/ilgcc/app/email/SendGridValidationResponseBodyTest.java
  src/test/java/org/ilgcc/app/submission/actions/ValidateProviderEmailTest.java
  src/test/java/org/ilgcc/app/submission/actions/ValidateProviderEmailWhenInputIsPresentTest.java
  src/test/java/org/ilgcc/app/utils/SendGridValidationResponseBodyBuilder.java
Labels: Ready For Review

#1455 [CCAP-837] Updating Hikari settings
  src/main/resources/application.yaml
Labels: Ready For Review

#1454 [CCAP-836] Updating CCMS job to take UUID instead of full Submission
  src/main/java/org/ilgcc/app/submission/actions/SendProviderRegistrationAndFamilyPayloadToCCMS.java
  src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java
  src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayload.java
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
  src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
Labels: Ready For Review

#1453 [CCAP-784] - implements registration-tax-id-itin screen
  src/main/java/org/ilgcc/app/submission/conditions/ProviderChoseItinTaxIdType.java
  src/main/java/org/ilgcc/app/submission/conditions/ProviderItinRegistrationForInHomeCare.java
  src/main/java/org/ilgcc/app/submission/conditions/ProviderSsnRequiredForInHomeCare.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/providerresponse/registration-tax-id-itin.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationWithItinJourneyTest.java
Labels: Ready For Review

#1484 [CCAP-849] Removing unused CCMS config values
  src/main/java/org/ilgcc/app/config/CCMSApiConfiguration.java
  src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java
  src/main/resources/application.yaml
Labels: Ready For Review

#1476 [CCAP-783] Update provider response registration-tax-id.html screen
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/templates/providerresponse/registration-payment-tax-id.html
  src/main/resources/templates/providerresponse/registration-tax-id.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationWithITINJourneyTest.java
Labels: Ready For Review

#1452 [CCAP-803] - reroutes to after-submit-contact-provider when applicant…
  src/main/resources/application.yaml
  src/main/resources/templates/fragments/screens/choose-messaging-method.html
  src/main/resources/templates/fragments/screens/find-provider.html
Labels: Do not merge, Ready For Review

#1494 [CCAP-852] Handling NPEs that happen because we skip around in the flow
  src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
  src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
  src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java
Labels: Ready to Merge

#1491 [CCAP-812] update content of providerresponse provider number screen
  src/main/resources/messages.properties
  src/main/resources/templates/providerresponse/provider-number.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderResponseWithFEINJourneyTest.java
Labels: Ready to Merge

#1496 [CCAP-806] - missing provider id and fein for provider response
  src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
  src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerTest.java
Labels: Ready to Merge

#1489 [CCAP-715] - limit site administered site routing to active sdas
  src/main/java/org/ilgcc/app/data/CCMSDataService.java
  src/main/java/org/ilgcc/app/data/CCMSDataServiceImpl.java
  src/main/java/org/ilgcc/app/data/ResourceOrganizationRepository.java
  src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java
  src/main/java/org/ilgcc/app/submission/router/ApplicationRoutingServiceImpl.java
  src/test/java/org/ilgcc/app/data/ProviderAndSiteAdministeredResourceOrganizationTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
  src/test/java/org/ilgcc/app/submission/actions/SetResourceOrganizationTest.java
Labels: Ready For Review

#1501 [CCAP-813] create new providerresponse fein screen
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/submission/conditions/HasFEIN.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/templates/providerresponse/fein.html
  src/main/resources/templates/providerresponse/paid-by-ccap.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderResponseWithFEINJourneyTest.java
Labels: Ready For Review

#1503 [CCAP-783] modify copy and conditional logic
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/submission/conditions/ProviderChoseITINTaxIdType.java
  src/main/resources/messages.properties
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationWithITINJourneyTest.java
  src/test/java/org/ilgcc/app/submission/conditions/ProviderChoseITINTaxIdTypeTest.java
Labels: Ready For Review

#1510 [CCAP-860] NPE in ProviderApplicationPreparer
  src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
Labels: Ready For Review

#1509 [CCAP-808] - tests that FEIN is properly set
  src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerTest.java
Labels: Ready For Review

#1504 [CCAP-857] - set expiration date and status
  src/main/java/org/ilgcc/app/inputs/Gcc.java
  src/main/java/org/ilgcc/app/submission/actions/GenerateShortLinkAndStoreProviderApplicationStatus.java
  src/main/java/org/ilgcc/app/submission/actions/GenerateShortLinks.java
  src/main/resources/flows-config.yaml
  src/main/resources/templates/fragments/screens/child-care-provider-info.html
  src/test/java/org/ilgcc/app/submission/actions/GenerateShortLinkAndStoreProviderApplicationStatusTest.java
  src/test/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayloadTest.java
Labels: Ready For Review

#1512 [CCAP-864] Rename TransmissionsRecurringJob
  src/main/java/org/ilgcc/jobs/ProviderResponseRecurringJob.java
  src/test/java/org/ilgcc/jobs/ProviderResponseRecurringJobTest.java
Labels: Ready For Review

#1507 [CCAP-814] Create provider-id-fein screen
  src/main/java/org/ilgcc/app/inputs/Providerresponse.java
  src/main/java/org/ilgcc/app/submission/actions/ValidateFEINIsNotBlank.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/fragments/inputs/overrides/text.html
  src/main/resources/templates/providerresponse/provider-id-fein.html
  src/main/resources/templates/providerresponse/registration-tax-id-ein.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
Labels: Ready For Review

#1505 [CCAP-815] create new providerresponse confirm application submission no response screen
  src/main/java/org/ilgcc/app/submission/actions/GetCCRRNameFromFamilySubmission.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/providerresponse/confirm-application-submission-no-response.html
  src/main/resources/templates/providerresponse/fein.html
  src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderResponseWithFEINJourneyTest.java
  src/test/java/org/ilgcc/app/submission/actions/GetCCRRNameFromFamilySubmissionTest.java
Labels: Ready For Review
